### ISSUE TITLE
Traslate to English

### ISSUE THREAD

**Issue by arvanus** [sim1984/udr-book#1]
Hi, any (real) possibility of a translation to English?
Thanks

**Comment by sim1984** [comment]
May be. I would like this guide to be verified by the Firebird developers. But they don’t have time for this. In this case, the Firebird Foundation would seek out translation tools, as was the case with the Firebird 2.5 Language Reference.

I can translate the text myself, but the quality of English will not be very good.

**Comment by reevespaul** [comment]
I've used google to translate the text. The results are not too bad. It required some manual intervention but overall it has worked. Google does have trouble with a few cyrillic words. And gets a little confused when translating pascal source code. But apart from that the process was fairly easy and only took a few hours. Of course the translations have lots of Russian expressions but I think the text is understandable. And the examples compile.

I've got the translations locally in a git repo. The only thing I need to do now is add the licenses to the examples.

The next step is to make it available on github. I think the only way is to put them in a separate repo. It would be better if they were in this repo but I can't see how that could be co-ordinated. 

Has any one got any experience of multi-language repositories?

**Comment by arvanus** [comment]
Hi, I uploaded the PDF to this site:
www.onlinedoctranslator.com
Translated quite well, just the code blocks got messed but it's OK to read.
Thank you for this great job!
For me, this issue can be closed, but I'm guessing that will be useful for others too
