### ISSUE TITLE
Invalid Source Array with JSON and Varchar

### ISSUE THREAD

**Issue by arvanus** [sim1984/udr-book#2]
Hi, I'm testing the JSON sample, and in a select with VARCHAR(100), I'm getting this error
```
'Invalid source Array'
At function GETJSON
```
I'm using Delphi 10.3 at windows, compiling a 32biut DLL with Fb 3.0.6 built from source
Note, If I remove the varchar field from select, I got no error and everything work as expected 
Steps to reproduce on a new database UFT8 (tried with ISO8859_1 too):
```
CREATE TABLE TEST
(
  ID INTEGER NOT NULL,
  A INTEGER,
  B INTEGER,
  NAME VARCHAR(100),
  CONSTRAINT PK_TEST PRIMARY KEY (ID)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON TEST TO  SYSDBA WITH GRANT OPTION;



create function GetJson (
sql_text blob sub_type text,
sql_dialect smallint not null default 3
) returns blob sub_type text character set utf8
external name 'JsonUtils!getJson'
engine udr;
commit;

INSERT INTO TEST (ID, A, B, NAME) VALUES ('1', '1', '2', '1dskugdhsfgcuosdagcfWUYDVSO');

--No error
select GetJson('
select r.ID, r.A, r.B from TEST r

order by 1
') from RDB$DATABASE

--Error
select GetJson('
select r.ID, r.A, r.B, substring(r.name from 1 for 5) from TEST r
order by 1
') from RDB$DATABASE


```

**Comment by arvanus** [comment]
Note, I tried another test, to use writeJson function in a trigger, and I got this error:
`Invalid count (100)`
At line:
```
            StringValue := charset.GetString(TBytes(@CharBuffer), 0,
              metaLength);
```
I know that the size of the field is 100, but de data inside the buffer is much smaller ("1dskugdhsfgcuosdagcfWUYDVSO")

**Comment by sim1984** [comment]
Ok, I will check this out and fix it.

**Comment by sim1984** [comment]
The error cannot be reproduced on a database with charset UTF8 (creation and connection).
Please specify the conditions for reproduction.
P.S. Firebird x64 3.0.6

**Comment by arvanus** [comment]
Sorry, there is some really bizarre problem 
Restarted Fb service, and it worked, tried again 3 times, in the 4, got the error 
"Prove" that it worded:
`[{"ID":0,"A":1,"B":2,"NAME":"12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678\u0000\u0000"},{"ID":1,"A":1,"B":2,"NAME":"1dskugdhsfgcuosdagcfWUYDVSO"},{"ID":2,"A":1,"B":2,"NAME":"5"},{"ID":3,"A":1,"B":2,"NAME":"5"},{"ID":4,"A":2,"B":3,"NAME":"1"}]`
Then I reconnected, and the error occurred again :\
Looks like some king of leak 👎 😢 

PS: now, I'm unable to get the error, both in the trigger and in the GetJson
:|

**Comment by arvanus** [comment]
ps:
Wrong varchar ending:

```
UPDATE TEST SET 
NAME = '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789A'
WHERE ID = '2';
```

```
select GetJson('
select r.ID, r.A, r.B, name 
from TEST r
WHERE ID=2
order by 1
') from RDB$DATABASE
```

The procedure returned:
`[{"ID":2,"A":1,"B":2,"NAME":"12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678\u0000\u0000"}]`

The last 2 unicode digits is wrong (`\u0000\u0000`), could this be the problem?
Thanks

**Comment by sim1984** [comment]
Yes, I see it. Now I'm trying to fix it.

**Comment by sim1984** [comment]
Fixed in the source code of the example. I will correct the text in the book a little later.

**Comment by arvanus** [comment]
Same UTF chars in the end, I think you need to remove the "-2" from  `Move((pData + 2)^, CharBuffer, metaLength - 2);` at lines 330 and 339 
Doing it here fixed (I really don't use "Move" function so I'm not sure about it)

**Comment by sim1984** [comment]
In this case, Move can be omitted. In my example, VARCHAR works with Cyrillic characters, but so far everything is bad with CHAR (((

**Comment by sim1984** [comment]
Somewhere there is a corruption of memory. I'm too tired today. I will watch the code tomorrow.

**Comment by arvanus** [comment]
I could debug the dll with isql embedded
Looks like at this step:
            `Move((pData + 2)^, CharBuffer, metaLength - 2);`
CharBuffer is populated with 98 chars (need to remove the -2 in the end)
But here:
```
            StringValue := charset.GetString(TBytes(@CharBuffer),  0,
              charLength);
```
`TBytes(@CharBuffer)` passes as an empty TBytes

**Comment by arvanus** [comment]
Managed to make it work this way, please test with Cyrillic characters:
```
//  CharBuffer: array [0 .. 35766] of Byte; change to TBytes
  CharBuffer:TBytes;
...
            SetLength(CharBuffer, metaLength);
            Move((pData + 2)^, CharBuffer[0], metaLength); // - 2);
            StringValue := charset.GetString(CharBuffer, 0,
              charLength);
```

**Comment by sim1984** [comment]
Yes, all is well now. Thanks, I corrected the source code of the example.
